version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - api-server

  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./.elbit:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/elbit.db
